name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: dependencies
      run: |
        sudo add-apt-repository ppa:joseluisblancoc/gtsam-develop -y
        sudo apt-get install -y libboost-all-dev libeigen3-dev libgtsam-dev
    
    - name: "build"
      run: |
        mkdir build 
        cd build
        cmake ..
        make