version: 2
name: CI

on: [push]

jobs:
  full-u18.04-bionic:
    docker:
      - image: mrpt/mrpt-build-env:full-bionic
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update
            apt-get install software-properties-common -y
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            add-apt-repository ppa:joseluisblancoc/gtsam-develop -y
            apt-get install libmrpt-dev -y
            apt-get install libgtsam-dev -y